### ISSUE TITLE
Неточности в описании проекта

### ISSUE THREAD

**Issue by ghost** [cmc-haskell-2018/asteroidea#11]
Начнём с простого, с опечатки.
> Рассчитываем на отзывы, конструктивную криитку

Я, конечно, так себе специалист, однако по моему мнению, тут что-то не то.

>Данная программа является результатом интеллектуальной деятельности, которому предоставляется правовая охрана. Право на данный результат интеллектуальной деятельности принадлежит коллективу авторов совместно. Ни название Asteroidea, ни имена её авторов не могут быть использованы в качестве поддержки или продвижения продуктов, основанных на этом ПО без предварительного письменного разрешения.

Вы же используете MIT лицензию, какая ещё правовая охрана? Нет её.
Предоставляются полные права кому угодно, кто имеет копию и предоставил к ней текст вашей лицензии. Ни о каких предварительных письменных разрешениях, естественно, и речи быть не может.

**Comment by alvadia** [comment]
О! Есть реакция!
Спасибо за внимание. Очепяткам бой!
Часть про письменные разрешения нужно читать с позиции Гражданского кодекса РФ, часть 4.
Смотри комментарии к нему.
Правовая охрана предоставляется в форме лицензии MIT, "свобода не есть вседозволенность".

**Comment by ghost** [comment]
Ох. Что-то я затрудняюсь найти нужную выдержку. А можно ссылку/конкретное упоминание статьи?
У нас вроде бы статья 1286.1 ГК РФ. 

Припустим, что правовая охрана есть, это очень похоже на правду, однако письменные разрешения для MIT точно не нужны.

**Comment by alvadia** [comment]
Данная работа является программой для ЭВМ, соответственно на неё распространяются все положения ГК РФ, касающиеся программ для ЭВМ. В частности, она попадает под действие статьи 1225, откуда взята формулировка первого предложения.

Согласно статье 1228, «Право авторства, право на имя и иные личные неимущественные права автора неотчуждаемы и непередаваемы. Отказ от этих прав ничтожен. Авторство и имя автора охраняются бессрочно». Отсюда следует запрет использования имён авторов без разрешения. Выбор формы разрешения за авторами, и в данном случае конкретизирован до письменного разрешения. Наш проект есть совместное творчество четырёх человек, на что распространяются положения п.4 ст.1228. В соответствии с которым права на программу принадлежат коллективу авторов совместно.

Название программы является средством индивидуализации, благодаря которому мы её и находим, например, на Github. И также охраняется ГК РФ, согласно статье 1229 «Другие лица не могут использовать соответствующее ... средство индивидуализации без согласия правообладателя, за исключением случаев, предусмотренных настоящим Кодексом».

В связи с вышеизложенным и следует трактовать абзац "Данная программа является результатом интеллектуальной деятельности, которому предоставляется правовая охрана. Право на данный результат интеллектуальной деятельности принадлежит коллективу авторов совместно. Ни название Asteroidea, ни имена её авторов не могут быть использованы в качестве поддержки или продвижения продуктов, основанных на этом ПО без предварительного письменного разрешения".

Лицензия MIT охватывает только часть интеллектуальной собственности, и является базой данной лицензии, но никак не окончательным содержанием.

**Comment by ghost** [comment]
Большое спасибо за подробный ответ, возможно поможет когда-нибудь, по крайней мере довольно познавательно.

Соответственно, тема исчерпана, закрываю-с.
